-- SCHEMA: willy

-- DROP SCHEMA IF EXISTS willy CASCADE;

CREATE SCHEMA IF NOT EXISTS willy
    AUTHORIZATION capybara;

GRANT USAGE ON SCHEMA willy TO alex;

GRANT ALL ON SCHEMA willy TO capybara;

ALTER DEFAULT PRIVILEGES IN SCHEMA willy
GRANT ALL ON TABLES TO alex;

ALTER DEFAULT PRIVILEGES IN SCHEMA willy
GRANT ALL ON SEQUENCES TO alex;

ALTER DEFAULT PRIVILEGES IN SCHEMA willy
GRANT EXECUTE ON FUNCTIONS TO alex;

ALTER DEFAULT PRIVILEGES IN SCHEMA willy
GRANT USAGE ON TYPES TO alex;